### ISSUE TITLE
Error in App: Exception on anything /User

### ISSUE THREAD

**Issue by octobarian** [prettyokay-software/PiDrive#1]
192.168.1.165 - - [12/Aug/2020 15:22:15] "GET /favicon.ico HTTP/1.1" 404 -
ERROR in app: Exception on /user/register [POST]
Traceback (most recent call last):
  File "/home/pi/app/PiDrive/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1278, in _execute_context
    cursor, statement, parameters, context
  File "/home/pi/app/PiDrive/env/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: users

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/app/PiDrive/env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/app/PiDrive/env/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/app/PiDrive/env/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/app/PiDrive/env/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/app/PiDrive/env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/app/PiDrive/env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/app/PiDrive/env/lib/python3.7/site-packages/flask_user/user_manager.py", line 423, in register_stub
    return self.register_view()
  File "/home/pi/app/PiDrive/env/lib/python3.7/site-packages/flask_user/user_manager__views.py", line 462, in register_view
    if request.method == 'POST' and register_form.validate():
  File "/home/pi/app/PiDrive/env/lib/python3.7/site-packages/flask_user/forms.py", line 285, in validate
    if not super(RegisterForm, self).validate():
  File "/home/pi/app/PiDrive/env/lib/python3.7/site-packages/wtforms/form.py", line 318, in validate
    return super(Form, self).validate(extra)
  File "/home/pi/app/PiDrive/env/lib/python3.7/site-packages/wtforms/form.py", line 150, in validate
    if not field.validate(self, extra):
  File "/home/pi/app/PiDrive/env/lib/python3.7/site-packages/wtforms/fields/core.py", line 226, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/pi/app/PiDrive/env/lib/python3.7/site-packages/wtforms/fields/core.py", line 246, in _run_validation_chain
    validator(form, self)
  File "/home/pi/app/PiDrive/env/lib/python3.7/site-packages/flask_user/forms.py", line 46, in unique_email_validator
    if not user_manager.email_is_available(field.data):
  File "/home/pi/app/PiDrive/env/lib/python3.7/site-packages/flask_user/user_manager__utils.py", line 43, in email_is_available
    user, user_email = self.db_manager.get_user_and_user_email_by_email(new_email)
  File "/home/pi/app/PiDrive/env/lib/python3.7/site-packages/flask_user/db_manager.py", line 173, in get_user_and_user_email_by_email
    user = self.db_adapter.ifind_first_object(self.UserClass, email=email)
  File "/home/pi/app/PiDrive/env/lib/python3.7/site-packages/flask_user/db_adapters/sql_db_adapter.py", line 139, in ifind_first_object
    return query.first()
  File "/home/pi/app/PiDrive/env/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3397, in first
    ret = list(self[0:1])
  File "/home/pi/app/PiDrive/env/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3171, in __getitem__
    return list(res)
  File "/home/pi/app/PiDrive/env/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3503, in __iter__
    return self._execute_and_instances(context)
  File "/home/pi/app/PiDrive/env/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3528, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/pi/app/PiDrive/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1014, in execute
    return meth(self, multiparams, params)
  File "/home/pi/app/PiDrive/env/lib/python3.7/s

**Comment by prettyokay-software** [comment]
Did you run the 'make init_db' command to create the database? 

You'll also need to use manage.py to create the roles and an initial user
